# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    container_name: symfony-backend
    ports:
      - "8080:80"
    volumes:
      - ./alcazan-back-prod:/var/www/html
      - /var/www/html/var/cache
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/chusei
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./alcazan-front-prod:/usr/src/app
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chusei
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

volumes:
  db_data:
