version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: symfony-backend
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://symfony:symfony@mysql:3306/chusei
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: react-frontend

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"  # Exposer seulement le port 80 pour le web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chusei
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
